/* date = November 14th 2021 11:15 am */

#ifndef PHYSICS_SIM_CONFIG_H
#define PHYSICS_SIM_CONFIG_H

#define RIGHTMONITOR (-900)
#define DEFAULT_WINDOW_COORDX  0
#define DEFAULT_WINDOW_COORDY  10
#define DEFAULT_WINDOW_WIDTH  400
#define DEFAULT_WINDOW_HEIGHT 800


#endif //PHYSICS_SIM_CONFIG_H
