/* date = November 14th 2021 11:15 am */

#ifndef PHYSICS_SIM_CONFIG_H
#define PHYSICS_SIM_CONFIG_H


#define DEFAULT_WINDOW_COORDX  10
#define DEFAULT_WINDOW_COORDY  10
#define DEFAULT_WINDOW_WIDTH  800
#define DEFAULT_WINDOW_HEIGHT 1000


#endif //PHYSICS_SIM_CONFIG_H
